apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment-${TENANT_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-ok
  template:
    metadata:
      labels:
        app: restapi-ok
    spec:
      containers:
        - name: rest-api-container
          image: "aviot/rest-api:latest"
          ports:
            - name: port
              protocol: TCP
              containerPort: 8080
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: JANUS_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: JANUS_SERVICE_HOST
            - name: JANUS_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: JANUS_SERVICE_PORT
            - name: ROS_MASTER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: ROS_MASTER_SERVICE_HOST
            - name: ROS_MASTER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: ROS_MASTER_SERVICE_PORT
            - name: MONGODB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: MONGODB_DATABASE_NAME
            - name: MONGODB_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: MONGODB_SERVICE_HOST
            - name: MONGODB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-${TENANT_ID}
                  key: MONGODB_SERVICE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-services-${TENANT_ID}
spec:
  type: NodePort
  selector:
    app: restapi-ok
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
