apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviot-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aviot-fe
  template:
    metadata:
      labels:
        app: aviot-fe
    spec:
      containers:
        - name: aviot-fe
          image: aviot/frontend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aviot-fe
spec:
  type: NodePort
  selector:
    app: aviot-fe
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
