apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbapp-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbapp-fe
  template:
    metadata:
      labels:
        app: dbapp-fe
    spec:
      containers:
        - name: dbapp-fe
          image: aviot/frontend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dbapp-fe
spec:
  type: NodePort
  selector:
    app: dbapp-fe
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
