apiVersion: v1
kind: Service
metadata:
  name: wss
spec:
  selector:
    app: wss
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      #nodePort: 31015

    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
      #nodePort: 30785

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss
spec:
  selector:
    matchLabels:
      app: wss
  template:
    metadata:
      labels:
        app: wss
    spec:
      restartPolicy: Always
      containers:
        - image: aviot/ws-server:latest
          name: wss
          ports:
            - name: ws
              containerPort: 8080
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: WS_NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: WS_PORT
