apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      restartPolicy: Always
      hostname: mongo
      containers:
        - image: mongo:latest
          name: mongo
          command: ["mongod"]
          args: ["--dbpath", "/data/db", "--bind_ip_all"]
          ports:
            - containerPort: 27017
#        volumeMounts:
#            - name: mongo
#              mountPath: /data/db
#      volumes:
#        - name: mongo
#          awsElasticBlockStore:
#            volumeID: aws://[aws-region-id]/[ebs-volume-id]
#            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      #nodePort: 32681
