apiVersion: v1
kind: Service
metadata:
  name: mynginxsvc
spec:
  type: NodePort
  selector:
    myapp: mynginxapp
  ports:
  - port: 80
    nodePort: 30180
    name: http
  - port: 443
    nodePort: 31443
    name: https
#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-echo
#spec:
#  type: NodePort
#  selector:
#    app: hello-echo
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 80
#      nodePort: 30036

kubectl run mypod --generator=run-pod/v1 --image=nginx --port=80 --labels="myapp=mynginxapp"
