apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdn-wise-controller
  labels:
    app.kubernetes.io/name: sdn-wise-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdn-wise-controller
  template:
    metadata:
      labels:
        app: sdn-wise-controller
    spec:
      containers:
        - name: n2nedgecontainer
          image: "aviot/n2nimage:latest"
          command: ["/bin/sh", "-c"]
          args:
            # notice -f at end to keep in foreground because its the only command, and NO dhcp client
            # and the fixed UDP port so that i can open it on AWS security group of the cluster's nodes
            # in order to enable P2P fast communication between nearby nodes
            - /edge -u 0 -g 0 -r -a $(N2N_IP_CONTROLLER) -c $(COM_NAME) -k $(COM_PASSWORD) -l $(SUPERNODE_URL) -p $(SUPERNODE_PORT_UDP) && ping ${DNS_SERVER_ADDRESS} -n -i 2;
          #the following is equivalent to running the container as:
          #docker run --cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun BLA BLA
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: "/dev/net/tun"
              name: dev-net-tun
              readOnly: true
          env:
            - name: COM_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: COM_NAME
            - name: COM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: COM_PASSWORD
            - name: SUPERNODE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: SUPERNODE_URL
            - name: SUPERNODE_PORT_UDP
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: SUPERNODE_PORT_UDP
            - name: N2N_IP_CONTROLLER
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: N2N_IP_CONTROLLER
        - name: sdn-wise-controller
          image: aviot/sdn-wise-controller:latest
          ports:
            - containerPort: 3000
            - containerPort: 5000
      dnsConfig:
        nameservers:
          - ${DNS_SERVER_ADDRESS}
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: v1
kind: Service
metadata:
  name: sdn-wise-controller
spec:
  type: NodePort
  selector:
    app: sdn-wise-controller
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
      name: port-socket
    - port: 5000
      targetPort: 5000
      nodePort: 30050
      name: port-sink
