apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdn-wise-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdn-wise-controller
  template:
    metadata:
      labels:
        app: sdn-wise-controller
    spec:
      containers:
        - name: n2nedgecontainer
          image: "aviot/n2nimage:latest"
          command: ["/bin/sh", "-c"]
          args:
            # keep the dhcp client running in foreground with -f
            # and the fixed UDP port so that i can open it on AWS security group of the cluster's nodes
            # in order to enable P2P fast communication between nearby nodes
            - /edge -u 0 -g 0 -r -a $(N2N_IP_CONTROLLER) -c $(COM_NAME) -k $(COM_PASSWORD) -l $(SUPERNODE_URL) -p $(SUPERNODE_PORT_UDP) && ping ${DNS_SERVER_ADDRESS} -n -i 2;
          #the following is equivalent to running the container as:
          #docker run --cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun BLA BLA
          ports:
            - name: port
              protocol: UDP
              containerPort: 42479
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: N2N_IP_CONTROLLER
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: N2N_IP_CONTROLLER
            - name: COM_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: COM_NAME
            - name: COM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: COM_PASSWORD
            - name: SUPERNODE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: SUPERNODE_URL
            - name: SUPERNODE_PORT_UDP
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: SUPERNODE_PORT_UDP
            - name: DEVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-aviot
                  key: DEVICE_NAME
          volumeMounts:
            - mountPath: "/dev/net/tun"
              name: dev-net-tun
              readOnly: true
          resources: {}
        - image: aviot/sdn-wise-controller:latest
          imagePullPolicy: Always
          name: sdn-wise-controller
          ports:
          - containerPort: 3000
            protocol: TCP
          - containerPort: 5000
            protocol: TCP
          volumeMounts:
            - mountPath: "/dev/net/tun"
              name: dev-net-tun
              readOnly: true
          resources: {}
      dnsConfig:
        nameservers:
          - ${DNS_SERVER_ADDRESS}
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: v1
kind: Service
metadata:
  name: sdn-wise-controller
spec:
  type: NodePort
  selector:
    app: sdn-wise-controller
  ports:
    - name: port-socket
      port: 3000
      targetPort: 3000
      nodePort: 30030
    - name: port-sink
      port: 5000
      targetPort: 5000
      nodePort: 30050