apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-echo
  template:
    metadata:
      labels:
        app: hello-echo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-echo-services
spec:
  type: NodePort
  selector:
    app: hello-echo
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80 # targetPort: http-port
    - protocol: UDP
      port: 9000
      name: utp-test
      targetPort: 80 # targetPort: http-port
